In [19]:
import pandas as pd
import numpy  as np
from sklearn  import linear_model
from scipy.stats import pearsonr
# feture el ertbat kwi mabin el ma bin el variable ex:area w el price (-1,1) 
# lkol feture m3 el price 
# 34an 3awz a3ml preduction ll price 
# 34an a3ml prediction bib2a 3n tre2 feture 

In [20]:
df = pd.read_csv("homePrices.csv")
df


area  bedRoom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  560000
2  3200      NaN   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [21]:
import math 
median_bedRoom = math.floor(df.bedRoom.median())
median_bedRoom

3

In [22]:
df.bedRoom =df.bedRoom.fillna(median_bedRoom)
df


area  bedRoom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  560000
2  3200      3.0   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [23]:
corr_area, _ = pearsonr(df['area'], df['price'])
corr_bedRoom, _ = pearsonr(df['bedRoom'], df['price'])
corr_age, _ = pearsonr(df['age'], df['price'])
print(f'corr_area: {corr_area}\n,corr_bedRoom: {corr_bedRoom}\n,corr_age:{corr_age}')

corr_area: 0.86296805047494
,corr_bedRoom: 0.7754466511055428
,corr_age:-0.60962046805321


In [24]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedRoom']],df.price)

LinearRegression()

In [25]:
reg.coef_

array([   97.40802676, 38127.090301  ])

In [26]:
reg.intercept_

158244.1471571906

In [31]:
reg.predict([[3000,3]])

array([564849.49832776])

In [34]:
141.5*3000 -29850.*3  

334950.0

In [32]:
reg.predict([[2500,4]])

array([554272.57525084])

In [36]:
141.5*2500 -29850.*4 

234350.0